[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.9,<3.15"
pandas = ">=2.1.1,<4"
ruff = ">=0.12.7,<0.16"

[pypi-dependencies]
nuremics-labs = { path = ".", editable = true }
nuremics = { path = "../nuremics", editable = true }

[tasks]
ruff-check = "ruff check"
ruff-fix = "ruff check --fix"

[feature.DEMO_APP.dependencies]
matplotlib = ">=3.9.4,<4"
pygame = ">=2.6.1,<3"
pymunk = ">=7.0.1,<8"
xlsxwriter = ">=3.2.3,<4"
openpyxl = ">=3.1.5,<4"

[feature.DEMO_APP.tasks]
DEMO_APP = "python ./src/nuremics_labs/apps/general/DEMO_APP/system.py"

[environments]
demo = ["DEMO_APP"]
